// <auto-generated />
using Beryl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beryl.Migrations
{
    [DbContext(typeof(BerylSqliteContext))]
    partial class BerylSqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Beryl.Models.Redirect", b =>
                {
                    b.Property<int>("RedirectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("RedirectId");

                    b.ToTable("Redirects");

                    b.HasData(
                        new
                        {
                            RedirectId = 1,
                            Url = "http://www.google.com"
                        },
                        new
                        {
                            RedirectId = 2,
                            Url = "http://www.amazon.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
